# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20170419_1428'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topiccommentmodel',
            table='topic_comment',
        ),
        migrations.AlterModelTable(
            name='topicmodel',
            table='topic',
        ),
    ]
