# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0007_auto_20171109_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiccommentmodel',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='topicnodemodel',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='topicnodemodel',
            name='node_name',
        ),
        migrations.AddField(
            model_name='topiccommentmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicnodemodel',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicnodemodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicnodemodel',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='topiccommentmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topiccommentmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.TopicModel'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topicnodemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
